### ISSUE TITLE
ORPort is not configured correctly

### ISSUE THREAD

**Issue by lunarthegrey** [nvjacobo/webtunnel#6]
When enabling Tor daemon logs, the following can be observed:

```
Dec 02 06:23:24.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Dec 02 06:23:24.000 [notice] Opening Control listener on /run/tor/control
Dec 02 06:23:24.000 [notice] Opened Control listener connection (ready) on /run/tor/control
Dec 02 06:23:24.000 [warn] The IPv4 ORPort address 127.0.0.1 does not match the descriptor address X.X.X.X. If you have a static public IPv4 address, use 'Address <IPv4>' and 'OutboundBindAddress <IPv4>'. If you are behind a NAT, use two ORPort lines: 'ORPort <PublicPort> NoListen' and 'ORPort <InternalPort> NoAdvertise'.
Dec 02 06:23:24.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Dec 02 06:23:24.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Dec 02 06:23:24.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Dec 02 06:23:24.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Dec 02 06:23:24.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Dec 02 06:23:24.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Dec 02 06:23:24.000 [notice] Bootstrapped 100% (done): Done
```

This is due to:

https://github.com/nvjacobo/webtunnel/blob/deb66f4f644963d96f0a0d97443efb32aee99bd7/templates/torrc.j2#L2

I believe this should simply be set to `auto` and listen on all interfaces.

For example, in the Docker webtunnel image it simply assigns a random port and doesn't only listen on localhost: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel/-/blob/main/release/container/start-tor.sh?ref_type=heads#L38

The current state of this template actually seems to break WT bridges entirely.

**Comment by lunarthegrey** [comment]
I tested my bridge with it set to localhost and it wouldn't work at all. Setting it to `auto` fixes the issue entirely and the bridge is usable. Without an ORPort listening on a public interface the bridges will be unusable.

**Comment by lunarthegrey** [comment]
PR opened https://github.com/nvjacobo/webtunnel/pull/7

**Comment by nvjacobo** [comment]
Hi @lunarthegrey 

Thanks. I am using the documentation for torrc: 

https://community.torproject.org/relay/setup/webtunnel/source/

I will check more later in a fresh installation and return here. Did you try with ExtORPort auto and SocksPort 0?

**Comment by nvjacobo** [comment]
Hi @lunarthegrey 

I tested on fresh installation, and I had the same error but it doesn't impact the operation of the tunnel. Are you running multiple bridges on the same box? Maybe that is why you configured IP:auto instead of 127.0.0.1:auto

**Comment by lunarthegrey** [comment]
I tested a WT bridge in Tor browser with the `127.0.0.1:auto` set and I was unable to connect to my bridge. When I removed it and set it to `auto` it started working. I noticed that on Tor metrics my bridges were consistently showing up then down, and now they're working fine with it set to `auto`.

I suspect the documentation for the source build may be wrong, as the Docker version doesn't use localhost either.

How I tested the WT bridges after setting them up via this Ansible role was copy https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel/-/blob/main/release/container/get-bridge-line.sh onto the WT bridge server, enable Tor logs in `/etc/tor/torrc`:

```
Log notice file /var/log/tor/log
Log notice stdout
```

Then restart the Tor service. After a while, run the script and it will output the bridge line you can put into Tor browser, just grab the full URL from your `/etc/tor/torrc` as it only outputs a partial line.

**Comment by nvjacobo** [comment]
Hi, @lunarthegrey 

I understand the documentation is not wrong. it's using a new undocumented feature: blocking ORPort so censors can't discover bridges by looking for their orport by exposing bridges orport, it's quite trivial for censors in russia/china to block bridges, According to what Gus explained to me, and it's fine to ignore that log message. I hope this helps. 

Thanks, Jacobo

**Comment by lunarthegrey** [comment]
Thanks @nvjacobo!

It looks like you're correct. I tested again and did not have the same issue with `127.0.0.1:auto`. There must have been an issue at the time of my previous test that was unrelated to the config. I'll go ahead and close the issue.

I wonder if the Docker image should be updated if that's the case with ORPort, as it doesn't look to be using localhost: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel/-/blob/main/release/container/start-tor.sh?ref_type=heads#L38 - unless that variable is defined as `127.0.0.1:auto` as well.
